
```{r}


library(circlize)
library(dplyr)

# Load your data
data <- read.csv("/Users/yuqingwu/UChicago_MSDS/Part-time/BSD/plotdata.csv")

selected_microbiomes <- c('UPDASV323','UPDASV019','UPDASV018','UPDASV317','UPDASV110','UPDASV458','UPDASV209','UPDASV412','UPDASV150','UPDASV314','UPDASV051','UPDASV310')

filtered_data <- data %>%
  filter(Index %in% selected_microbiomes) %>%
  select(Index, PM25_coef, Ghrelin_coef, Resistin_coef, Insulin_coef) %>%
  rename(PM2.5 = PM25_coef,
         Ghrelin = Ghrelin_coef,
         Resistin = Resistin_coef,
         Insulin = Insulin_coef)

# Melt the data into long format
library(tidyr)
chord_data <- filtered_data %>%
  gather(key = "Metric", value = "Coefficient", -Index)

# Rename columns for circlize
colnames(chord_data) <- c("source", "target", "value")
print(chord_data)

```


```{r}
# Assign colors to the edges based on the source and target values
chord_data$color <- ifelse(chord_data$target %in% c("PM2.5", "Ghrelin", "Resistin", "Insulin"), 
                           "deepskyblue3", "red")

# Initialize the chord diagram
circos.clear()
circos.par(gap.after = c(rep(2, length(unique(chord_data$source)) - 1), 10, 
                         rep(2, length(unique(chord_data$target)) - 1), 10))

# Define the sector colors
sectors <- unique(c(chord_data$source, chord_data$target))
sector_colors <- rep(c("burlywood1", "pink"), times = c(length(unique(chord_data$source)), 
                                                 length(unique(chord_data$target))))
names(sector_colors) <- sectors

# Plot the chord diagram
chordDiagram(chord_data, annotationTrack = "grid", preAllocateTracks = 1,
             grid.col = sector_colors, col = chord_data$color)

# Add titles and labels
circos.track(track.index = 1, panel.fun = function(x, y) {
  circos.text(CELL_META$xcenter, CELL_META$ylim[1], CELL_META$sector.index, 
              facing = "clockwise", niceFacing = TRUE, adj = c(0, 0.5))
}, bg.border = NA)
title("Relationships between Microbiomes, PM2.5 and Biomarkers")

```


```{r}

# Load your data
data <- read.csv("C:\\Users\\yuqingw1\\Workfolder\\plotdata.csv")

selected_microbiomes <- c('UPDASV323','UPDASV019','UPDASV018','UPDASV317','UPDASV110','UPDASV458','UPDASV209','UPDASV412','UPDASV150','UPDASV314','UPDASV051','UPDASV310')

filtered_data <- data %>%
  filter(Index %in% selected_microbiomes) %>%
  select(Index, PM25_coef, Ghrelin_coef, Resistin_coef, Insulin_coef) %>%
  rename(PM2.5 = PM25_coef,
         Ghrelin = Ghrelin_coef,
         Resistin = Resistin_coef,
         Insulin = Insulin_coef)

# Melt the data into long format
chord_data <- filtered_data %>%
  gather(key = "Metric", value = "Coefficient", -Index)

filtered_data <- data %>%
  filter(Index %in% selected_microbiomes) %>%
  select(Index, PM25_coef, Ghrelin_coef, Resistin_coef, Insulin_coef) %>%
  rename(PM2.5 = PM25_coef,
         Ghrelin = Ghrelin_coef,
         Resistin = Resistin_coef,
         Insulin = Insulin_coef)

# Melt the data into long format
library(tidyr)
chord_data <- filtered_data %>%
  gather(key = "Metric", value = "Coefficient", -Index)

# Create Air_Pollution column
chord_data <- chord_data %>%
  mutate(Air_Pollution = ifelse(Metric == "PM2.5", "PM2.5", "NA"),
         Biomarker = ifelse(Metric == "Ghrelin", "Ghrelin",
                   ifelse(Metric == "Insulin", "Insulin",
                   ifelse(Metric == "Resistin", "Resistin", "NA"))),
         Metric = factor(Metric, levels = c("PM2.5", "Ghrelin", "Resistin", "Insulin")))

# Filter out PM2.5 from the Metric column
chord_data <- chord_data %>%
  filter(Air_Pollution == "PM2.5" | Metric != "PM2.5")

# Plot the alluvial diagram
p <- ggplot(data = chord_data,
            aes(axis1 = Air_Pollution, axis2 = Index, axis3 = Biomarker, y = abs(Coefficient))) +
  geom_alluvium(aes(fill = Metric)) +
  geom_stratum(aes(axis1 = Air_Pollution, axis2 = Index, axis3 = Biomarker), width = 1/3, na.rm = TRUE) +
  geom_text(stat = "stratum", aes(label = after_stat(stratum)), na.rm = TRUE, size = 2) +
  scale_x_discrete(limits = c("Air Pollution", "Microbiome", "Biomarker"), expand = c(.05, .05)) +
  theme_minimal() +
  ggtitle("Relationships between Microbiomes, PM2.5 and Biomarkers") +
  ylab("abs(Coefficient)") +
  theme(axis.text.x = element_text(size = 8, face = "bold"),
        axis.text.y = element_text(size = 8, face = "bold"),
        plot.title = element_text(size = 14, face = "bold"),
        legend.title = element_text(size = 10),      # Adjust legend title size
        legend.text = element_text(size = 8),       # Adjust legend text size
        strip.text = element_text(size = 8))        # Adjust facet label size

# Show the plot
print(p)

```





```{r}

library(ggalluvial)
library(ggplot2)
library(dplyr)
library(tidyr)
library(patchwork)

# Load your data
data <- read.csv("C:\\Users\\yuqingw1\\Workfolder\\plotdata.csv")

selected_microbiomes <- c('UPDASV323','UPDASV019','UPDASV018','UPDASV317','UPDASV110','UPDASV458','UPDASV209','UPDASV412','UPDASV150','UPDASV314','UPDASV051','UPDASV310')

filtered_data <- data %>%
  filter(Index %in% selected_microbiomes) %>%
  select(Index, PM25_coef, Ghrelin_coef, Resistin_coef, Insulin_coef) %>%
  rename(PM2.5 = PM25_coef,
         Ghrelin = Ghrelin_coef,
         Resistin = Resistin_coef,
         Insulin = Insulin_coef)

# Melt the data into long format
chord_data <- filtered_data %>%
  gather(key = "Metric", value = "Coefficient", -Index)

chord_data_pm25 <- chord_data %>%
  filter(Metric == "PM2.5") %>%
  rename(Air_Pollution = Metric,
         Microbiome = Index,
         Coefficient_pm25 = Coefficient)

# Prepare the data for microbiomes to biomarkers
chord_data_biomarkers <- chord_data %>%
  filter(Metric != "PM2.5") %>%
  rename(Biomarker = Metric,
         Microbiome = Index,
         Coefficient_biomarker = Coefficient)

# Concatenate the two datasets
alluvial_data_pm25 <- chord_data_pm25 %>%
  mutate(Biomarker = NA,
         Coefficient_biomarker = NA,
         Metric = Air_Pollution) %>%
  select(Air_Pollution, Microbiome, Biomarker, Coefficient_pm25, Coefficient_biomarker, Metric)

alluvial_data_biomarkers <- chord_data_biomarkers %>%
  mutate(Air_Pollution = NA,
         Coefficient_pm25 = NA,
         Metric = Biomarker) %>%
  select(Air_Pollution, Microbiome, Biomarker, Coefficient_pm25, Coefficient_biomarker, Metric)

alluvial_data <- bind_rows(alluvial_data_pm25, alluvial_data_biomarkers)


# Prepare the data for the alluvial plot
alluvial_data <- alluvial_data %>%
  mutate(Air_Pollution = ifelse(is.na(Air_Pollution), 'PM2.5', Air_Pollution),
         Biomarker = ifelse(is.na(Biomarker), c('Ghrelin', 'Ghrelin','Ghrelin','Ghrelin', 'Insulin', 'Insulin','Insulin','Insulin', 'Resistin', 'Resistin','Resistin','Resistin'), Biomarker),
         Coefficient = ifelse(!is.na(Coefficient_pm25), abs(Coefficient_pm25), abs(Coefficient_biomarker)),
         Coefficient_pm25 = ifelse(is.na(Coefficient_pm25), 0, Coefficient_pm25),
         Coefficient_biomarker = ifelse(is.na(Coefficient_biomarker), 0, Coefficient_biomarker),
        Metric = factor(Metric, levels = c("PM2.5", "Ghrelin", "Resistin", "Insulin")) )


# Plot the alluvial diagram
ggplot(
  #data = alluvial_data) +
  #geom_alluvium(aes(axis1 = Air_Pollution, axis2 = Microbiome, axis3 = Biomarker,
                    #y = abs(Coefficient), fill = Metric), na.rm = TRUE) +
  #geom_alluvium(aes(axis1 = Air_Pollution, axis2 = Microbiome, axis3 = Biomarker,
                    #y = abs(Coefficient_biomarker), fill = Metric), na.rm = TRUE) +
  #geom_text(stat = "stratum", aes(label = after_stat(stratum), axis1 = Air_Pollution, axis2 = Microbiome, axis3=Biomarker), na.rm = TRUE, check_overlap = FALSE, size=3) +
  
  data = alluvial_data,
              aes(axis1 = Air_Pollution, axis2 = Microbiome, axis3 = Biomarker, y = abs(Coefficient))) +
  geom_alluvium(aes(fill = Metric)) +
  geom_stratum(aes(axis1 = Air_Pollution, axis2 = Microbiome, axis3 = Biomarker), width = 1/3, na.rm = TRUE) +
  geom_text(stat = "stratum", aes(label = after_stat(stratum)), na.rm = TRUE, size = 2) +
  
  scale_x_discrete(limits = c("Air Pollution", "Microbiome", "Biomarker"), expand = c(.05, .05)) +
  theme_minimal() +
  ggtitle("Relationships between Microbiomes, PM2.5 and Biomarkers") +
  ylab("abs(Coefficient)") +
  theme(axis.text.x = element_text(size = 8, face = "bold"),
        axis.text.y = element_text(size = 8, face = "bold"),
        plot.title = element_text(size = 14, face = "bold"),
        legend.title = element_text(size = 10),      # Adjust legend title size
        legend.text = element_text(size = 8),       # Adjust legend text size
        strip.text = element_text(size = 8))        # Adjust facet label size


```



```{r}

library(ggalluvial)
library(ggplot2)
library(dplyr)
library(tidyr)
library(patchwork)
library(readxl)
library(stringr)

# Load your data
data <- read.csv("C:\\Users\\yuqingw1\\Workfolder\\plotdata.csv")
taxonIDname <- read_excel("C:\\Users\\yuqingw1\\Workfolder\\ProcessingData\\processing_4_microbiome\\taxonIDmappingdict.xlsx")

#selected_microbiomes <- c('UPDASV018','UPDASV009','UPDASV019','UPDASV020','UPDASV028','UPDASV071','UPDASV080','UPDASV084','UPDASV093','UPDASV110','UPDASV123','UPDASV152','UPDASV175','UPDASV200','UPDASV202','UPDASV203','UPDASV204','UPDASV244','UPDASV265','UPDASV294','UPDASV310','UPDASV316','UPDASV317','UPDASV319','UPDASV321','UPDASV322','UPDASV323','UPDASV329','UPDASV330','UPDASV363','UPDASV365','UPDASV412','UPDASV449','UPDASV451','UPDASV473','UPDASV482','UPDASV483','UPDASV492')

selected_microbiomes <- c('UPDASV018','UPDASV019','UPDASV028','UPDASV071','UPDASV084','UPDASV093','UPDASV110','UPDASV152','UPDASV200','UPDASV203','UPDASV204','UPDASV244','UPDASV265','UPDASV294','UPDASV316','UPDASV317','UPDASV319','UPDASV322','UPDASV323','UPDASV412','UPDASV482','UPDASV492')

filtered_data <- data %>%
  filter(Index %in% selected_microbiomes) %>%
  select(Index, PM25_coef, Ghrelin_coef, Resistin_coef, Insulin_coef) %>%
  rename(PM2.5 = PM25_coef,
         Ghrelin = Ghrelin_coef,
         Resistin = Resistin_coef,
         Insulin = Insulin_coef)

filtered_data <- taxonIDname %>%
  inner_join(filtered_data, by = c("newtaxonID" = "Index"))

# Define the custom function
extract_name <- function(row) {
  attlist <- str_split(row, ",")[[1]]

  if (attlist[length(attlist)] == 'nan') {
    if (attlist[length(attlist) - 1] != 'nan') {
      name <- paste('Family:', attlist[length(attlist) - 1])
    } else if (attlist[length(attlist) - 2] != 'nan') {
      name <- paste('Order:', attlist[length(attlist) - 2])
    } else if (attlist[length(attlist) - 3] != 'nan') {
      name <- paste('Class:', attlist[length(attlist) - 3])
    } else if (attlist[length(attlist) - 4] != 'nan') {
      name <- paste('Phylum:', attlist[length(attlist) - 4])
    } else {
      name <- paste('Kingdom:', attlist[length(attlist) - 5])
    }
  } else {
    name <- attlist[length(attlist)]
  }

  return(name)
}

# Assuming 'name' is the data frame and 'attribute' is the column
filtered_data <- filtered_data %>%
  mutate(newname = sapply(attribute, extract_name))




# Melt the data into long format
chord_data <- filtered_data %>%
  gather(key = "Metric", value = "Coefficient", -newname)

# Prepare the data for microbiomes to biomarkers
chord_data_biomarkers <- chord_data %>%
  filter(Metric %in% c("Ghrelin", "Resistin", "Insulin")) %>%
  rename(Biomarker = Metric,
         Microbiome = newname,
         Coefficient_biomarker = Coefficient)

chord_data_biomarkers$Coefficient_biomarker <- as.numeric(chord_data_biomarkers$Coefficient_biomarker)

# Prepare the data for the alluvial plot
alluvial_data <- chord_data_biomarkers %>%
  mutate(
    Coefficient = abs(Coefficient_biomarker),
    Metric = factor(Biomarker, levels = c("Ghrelin", "Resistin", "Insulin"))
  )

### plot figure
ggplot(data = alluvial_data,
       aes(axis1 = Microbiome, axis2 = Biomarker, y = abs(Coefficient))) +
  geom_alluvium(aes(fill = Metric)) +
  geom_stratum(aes(axis1 = Microbiome, axis2 = Biomarker), width = 0.25, na.rm = TRUE, fill = c(rep('white', length(unique(alluvial_data$Microbiome))), 'darkseagreen2', 'lightsteelblue2', 'rosybrown2')) +
  #geom_text(stat = "stratum", aes(label = after_stat(stratum)), na.rm = TRUE, size = 12) +  # Adjust size here
  geom_text(stat = "stratum", aes(label = Microbiome, axis1 = Microbiome), size = 12, hjust = 0.5, vjust = 0.5) +  # Custom microbiome text
  geom_text(stat = "stratum", aes(label = Biomarker, axis2 = Biomarker), size = 18, hjust = 0.5, vjust = 0.5) +  # Custom biomarker text
  
  scale_x_discrete(limits = c("Microbiome", "Biomarker"), expand = c(.05, .05)) +
  theme_minimal() +
  ggtitle("Relationships between Microbiomes and Biomarkers") +
  #ylab("abs(Coefficient)") +
  ylab(NULL) +  # Remove y-axis label
  theme(
    axis.text.x = element_text(size = 40, face = "bold"),
    axis.text.y = element_text(size = 40, face = "bold"),
    plot.title = element_text(hjust = 0.5, size = 52, face = "bold"),
    legend.position = "none",  # Remove the legend
    #strip.text = element_text(size = 20),         # Adjust facet label size
    strip.text = element_blank(),
    plot.margin = unit(c(1,1,1,1), "cm")         # Adjust plot margins to fit text
  ) +
  theme(axis.text.y = element_text(size = 25))  # Adjust y-axis text size to fit grid


# Adjust the plot dimensions
ggsave("alluvial_plot.png", width = 40, height = 40, units = "in", bg = "white")
```
















